
/// This file was generated at 10:09:52 AM on the Monday, March 1, 2021 (UTC).

using System;
using System.Collections.Generic;
using System.Globalization;
using Xamarin.Forms;

namespace TODO
{
    /// <summary>
    /// Layout constants converter.
    /// </summary>
	public class LayoutConstantsConverter : IValueConverter
    {
        readonly static IDictionary<string, Thickness> keyToThickness = new Dictionary<string, Thickness>()
         {
             { "P0", LayoutConstants.P0 },
             { "P", LayoutConstants.P },
             { "P1", LayoutConstants.P1 },
             { "P2", LayoutConstants.P2 },
             { "P3", LayoutConstants.P3 },
             { "P4", LayoutConstants.P4 },
             { "P5", LayoutConstants.P5 },
             { "Pl0", LayoutConstants.Pl0 },
             { "Pl", LayoutConstants.Pl },
             { "Pl1", LayoutConstants.Pl1 },
             { "Pl2", LayoutConstants.Pl2 },
             { "Pl3", LayoutConstants.Pl3 },
             { "Pl4", LayoutConstants.Pl4 },
             { "Pl5", LayoutConstants.Pl5 },
             { "Ps0", LayoutConstants.Ps0 },
             { "Ps", LayoutConstants.Ps },
             { "Ps1", LayoutConstants.Ps1 },
             { "Ps2", LayoutConstants.Ps2 },
             { "Ps3", LayoutConstants.Ps3 },
             { "Ps4", LayoutConstants.Ps4 },
             { "Ps5", LayoutConstants.Ps5 },
             { "Pt0", LayoutConstants.Pt0 },
             { "Pt", LayoutConstants.Pt },
             { "Pt1", LayoutConstants.Pt1 },
             { "Pt2", LayoutConstants.Pt2 },
             { "Pt3", LayoutConstants.Pt3 },
             { "Pt4", LayoutConstants.Pt4 },
             { "Pt5", LayoutConstants.Pt5 },
             { "Pr0", LayoutConstants.Pr0 },
             { "Pr", LayoutConstants.Pr },
             { "Pr1", LayoutConstants.Pr1 },
             { "Pr2", LayoutConstants.Pr2 },
             { "Pr3", LayoutConstants.Pr3 },
             { "Pr4", LayoutConstants.Pr4 },
             { "Pr5", LayoutConstants.Pr5 },
             { "Pe0", LayoutConstants.Pe0 },
             { "Pe", LayoutConstants.Pe },
             { "Pe1", LayoutConstants.Pe1 },
             { "Pe2", LayoutConstants.Pe2 },
             { "Pe3", LayoutConstants.Pe3 },
             { "Pe4", LayoutConstants.Pe4 },
             { "Pe5", LayoutConstants.Pe5 },
             { "Pb0", LayoutConstants.Pb0 },
             { "Pb", LayoutConstants.Pb },
             { "Pb1", LayoutConstants.Pb1 },
             { "Pb2", LayoutConstants.Pb2 },
             { "Pb3", LayoutConstants.Pb3 },
             { "Pb4", LayoutConstants.Pb4 },
             { "Pb5", LayoutConstants.Pb5 },
             { "Py0", LayoutConstants.Py0 },
             { "Py", LayoutConstants.Py },
             { "Py1", LayoutConstants.Py1 },
             { "Py2", LayoutConstants.Py2 },
             { "Py3", LayoutConstants.Py3 },
             { "Py4", LayoutConstants.Py4 },
             { "Py5", LayoutConstants.Py5 },
             { "Px0", LayoutConstants.Px0 },
             { "Px", LayoutConstants.Px },
             { "Px1", LayoutConstants.Px1 },
             { "Px2", LayoutConstants.Px2 },
             { "Px3", LayoutConstants.Px3 },
             { "Px4", LayoutConstants.Px4 },
             { "Px5", LayoutConstants.Px5 },
             { "Pltr0", LayoutConstants.Pltr0 },
             { "Pltr", LayoutConstants.Pltr },
             { "Pltr1", LayoutConstants.Pltr1 },
             { "Pltr2", LayoutConstants.Pltr2 },
             { "Pltr3", LayoutConstants.Pltr3 },
             { "Pltr4", LayoutConstants.Pltr4 },
             { "Pltr5", LayoutConstants.Pltr5 },
             { "Plrb0", LayoutConstants.Plrb0 },
             { "Plrb1", LayoutConstants.Plrb1 },
             { "Plrb2", LayoutConstants.Plrb2 },
             { "Plrb3", LayoutConstants.Plrb3 },
             { "Plrb4", LayoutConstants.Plrb4 },
             { "Plrb5", LayoutConstants.Plrb5 },
             { "M0", LayoutConstants.M0 },
             { "M", LayoutConstants.M },
             { "M1", LayoutConstants.M1 },
             { "M2", LayoutConstants.M2 },
             { "M3", LayoutConstants.M3 },
             { "M4", LayoutConstants.M4 },
             { "M5", LayoutConstants.M5 },
             { "Ml0", LayoutConstants.Ml0 },
             { "Ml", LayoutConstants.Ml },
             { "Ml1", LayoutConstants.Ml1 },
             { "Ml2", LayoutConstants.Ml2 },
             { "Ml3", LayoutConstants.Ml3 },
             { "Ml4", LayoutConstants.Ml4 },
             { "Ml5", LayoutConstants.Ml5 },
             { "Ms0", LayoutConstants.Ms0 },
             { "Ms", LayoutConstants.Ms },
             { "Ms1", LayoutConstants.Ms1 },
             { "Ms2", LayoutConstants.Ms2 },
             { "Ms3", LayoutConstants.Ms3 },
             { "Ms4", LayoutConstants.Ms4 },
             { "Ms5", LayoutConstants.Ms5 },
             { "Mt0", LayoutConstants.Mt0 },
             { "Mt", LayoutConstants.Mt },
             { "Mt1", LayoutConstants.Mt1 },
             { "Mt2", LayoutConstants.Mt2 },
             { "Mt3", LayoutConstants.Mt3 },
             { "Mt4", LayoutConstants.Mt4 },
             { "Mt5", LayoutConstants.Mt5 },
             { "Mr0", LayoutConstants.Mr0 },
             { "Mr", LayoutConstants.Mr },
             { "Mr1", LayoutConstants.Mr1 },
             { "Mr2", LayoutConstants.Mr2 },
             { "Mr3", LayoutConstants.Mr3 },
             { "Mr4", LayoutConstants.Mr4 },
             { "Mr5", LayoutConstants.Mr5 },
             { "Me0", LayoutConstants.Me0 },
             { "Me", LayoutConstants.Me },
             { "Me1", LayoutConstants.Me1 },
             { "Me2", LayoutConstants.Me2 },
             { "Me3", LayoutConstants.Me3 },
             { "Me4", LayoutConstants.Me4 },
             { "Me5", LayoutConstants.Me5 },
             { "Mb0", LayoutConstants.Mb0 },
             { "Mb", LayoutConstants.Mb },
             { "Mb1", LayoutConstants.Mb1 },
             { "Mb2", LayoutConstants.Mb2 },
             { "Mb3", LayoutConstants.Mb3 },
             { "Mb4", LayoutConstants.Mb4 },
             { "Mb5", LayoutConstants.Mb5 },
             { "My0", LayoutConstants.My0 },
             { "My", LayoutConstants.My },
             { "My1", LayoutConstants.My1 },
             { "My2", LayoutConstants.My2 },
             { "My3", LayoutConstants.My3 },
             { "My4", LayoutConstants.My4 },
             { "My5", LayoutConstants.My5 },
             { "Mx0", LayoutConstants.Mx0 },
             { "Mx", LayoutConstants.Mx },
             { "Mx1", LayoutConstants.Mx1 },
             { "Mx2", LayoutConstants.Mx2 },
             { "Mx3", LayoutConstants.Mx3 },
             { "Mx4", LayoutConstants.Mx4 },
             { "Mx5", LayoutConstants.Mx5 },
             { "Mltr0", LayoutConstants.Mltr0 },
             { "Mltr", LayoutConstants.Mltr },
             { "Mltr1", LayoutConstants.Mltr1 },
             { "Mltr2", LayoutConstants.Mltr2 },
             { "Mltr3", LayoutConstants.Mltr3 },
             { "Mltr4", LayoutConstants.Mltr4 },
             { "Mltr5", LayoutConstants.Mltr5 },
             { "Mlrb0", LayoutConstants.Mlrb0 },
             { "Mlrb", LayoutConstants.Mlrb },
             { "Mlrb1", LayoutConstants.Mlrb1 },
             { "Mlrb2", LayoutConstants.Mlrb2 },
             { "Mlrb3", LayoutConstants.Mlrb3 },
             { "Mlrb4", LayoutConstants.Mlrb4 },
             { "Mlrb5", LayoutConstants.Mlrb5 },
         };

        readonly static IDictionary<string, double> keyToDouble = new Dictionary<string, double>()
         {
             { "S0", LayoutConstants.S0 },
             { "S", LayoutConstants.S },
             { "S1", LayoutConstants.S1 },
             { "S2", LayoutConstants.S2 },
             { "S3", LayoutConstants.S3 },
             { "S4", LayoutConstants.S4 },
             { "S5", LayoutConstants.S5 },
         };

        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            // TODO add logic here
            throw new NotImplementedException();
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            // TODO add logic here
            throw new NotImplementedException();
        }
    }
}
